version: '3.8'

services:
  # 后端API服务
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=123456
      - REDIS_URL=redis://redis:6379
      - CORS_ORIGINS=http://localhost:3000,http://frontend:3000
    volumes:
      - ../qa:/app/qa  # 挂载现有问答系统
      - ../backend:/app/backend  # 挂载现有后端
      - ../models:/app/models  # 挂载模型文件
      - ../data:/app/data  # 挂载数据文件
    depends_on:
      - neo4j
      - redis
    networks:
      - algokg-network

  # 前端React应用
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - REACT_APP_WS_URL=ws://localhost:8000
    depends_on:
      - backend
    networks:
      - algokg-network

  # Neo4j图数据库
  neo4j:
    image: neo4j:5.13
    ports:
      - "7474:7474"  # Web界面
      - "7687:7687"  # Bolt协议
    environment:
      - NEO4J_AUTH=neo4j/123456
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    networks:
      - algokg-network

  # Redis缓存
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - algokg-network

  # Nginx反向代理（生产环境）
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl  # SSL证书目录
    depends_on:
      - backend
      - frontend
    networks:
      - algokg-network
    profiles:
      - production

volumes:
  neo4j_data:
  neo4j_logs:
  redis_data:

networks:
  algokg-network:
    driver: bridge
